### ISSUE TITLE
GPL licence?

### ISSUE THREAD

**Issue by drphilmarshall** [sbird/fs-neutrino#1]
Hi Simeon! Great talking to you at coffee at #cosmomlstat just now. If Gadget3 is GPL-licensed, do your fs-neutrino patches need to be as well? Even while Gadget3 is not publically released?

**Comment by sbird** [comment]
Hi Phil! Indeed it should be - the intention was to release it as modified BSD, just in case someone has a CDDL licensed code somewhere down the line. I see I didn't actually add a license text, so let me do that.

**Comment by sbird** [comment]
Fixed by: 05d0b46e066e6850577627c52036e11bcac4eae8
